package com.proximity.app;
import android.Manifest; import android.app.*; import android.bluetooth.*; import android.bluetooth.le.*; import android.content.*; import android.content.pm.PackageManager; import android.graphics.*; import android.os.*; import android.view.*; import java.util.*;
public class MainActivity extends Activity {
 RadarView radar; BluetoothLeScanner scanner; final Map<String,D> ds=new LinkedHashMap<>();
 public void onCreate(Bundle b){super.onCreate(b);radar=new RadarView(this);setContentView(radar);if(Build.VERSION.SDK_INT>=31&&checkSelfPermission(Manifest.permission.BLUETOOTH_SCAN)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.BLUETOOTH_SCAN,Manifest.permission.BLUETOOTH_CONNECT},7);else scan();}
 public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==7)scan();}
 void scan(){BluetoothManager m=(BluetoothManager)getSystemService(BLUETOOTH_SERVICE);if(m==null||m.getAdapter()==null||!m.getAdapter().isEnabled()){radar.s="BLUETOOTH OFF";radar.invalidate();return;}scanner=m.getAdapter().getBluetoothLeScanner();if(scanner==null)return;try{scanner.startScan(null,new ScanSettings.Builder().setScanMode(ScanSettings.SCAN_MODE_LOW_LATENCY).build(),cb);radar.s="LIVE SCAN";}catch(SecurityException e){radar.s="PERMISSION NEEDED";}radar.invalidate();}
 final ScanCallback cb=new ScanCallback(){public void onScanResult(int t,ScanResult r){String id;try{id=r.getDevice().getAddress();}catch(Exception e){id="d"+r.hashCode();}String n=r.getScanRecord()==null?null:r.getScanRecord().getDeviceName();if(n==null||n.isEmpty())n="Nearby device";D d=ds.get(id);if(d==null){d=new D(id,n,r.getRssi());ds.put(id,d);}d.n=n;d.r=(int)(d.r*.65+r.getRssi()*.35);d.t=System.currentTimeMillis();if(ds.size()>40)ds.remove(ds.keySet().iterator().next());radar.invalidate();}};
 protected void onDestroy(){super.onDestroy();try{if(scanner!=null)scanner.stopScan(cb);}catch(Exception e){}}
 class D{String id,n;int r;long t;D(String i,String n,int r){id=i;this.n=n;this.r=r;t=System.currentTimeMillis();}double m(){return Math.pow(10.0,(-59-r)/(22.0));}}
 class RadarView extends View{Paint p=new Paint(3),tx=new Paint(3);String s="STARTING…";RadarView(Context c){super(c);setBackgroundColor(Color.rgb(7,17,15));}
 protected void onDraw(Canvas c){super.onDraw(c);float w=getWidth(),h=getHeight(),cx=w/2,cy=Math.min(h*.40f,cx+125),R=Math.min(w*.43f,260);
 tx.setTypeface(Typeface.DEFAULT_BOLD);tx.setTextSize(40);tx.setColor(Color.WHITE);c.drawText("PROXIMITY",30,55,tx);tx.setTypeface(Typeface.DEFAULT);tx.setTextSize(18);tx.setColor(Color.rgb(101,230,180));c.drawText(s+"  •  "+ds.size()+" SIGNALS",32,89,tx);
 p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(2);p.setColor(Color.rgb(42,79,68));for(int i=1;i<=4;i++)c.drawCircle(cx,cy,R*i/4,p);c.drawLine(cx-R,cy,cx+R,cy,p);c.drawLine(cx,cy-R,cx,cy+R,p);
 tx.setTextSize(14);tx.setColor(Color.rgb(126,153,145));c.drawText("~15 ft",cx+5,cy-R/4+18,tx);c.drawText("~30 ft",cx+5,cy-R/2+18,tx);c.drawText("~60 ft",cx+5,cy-R*3/4+18,tx);
 p.setStyle(Paint.Style.FILL);p.setColor(Color.rgb(101,230,180));c.drawCircle(cx,cy,12,p);tx.setColor(Color.WHITE);c.drawText("YOU",cx-15,cy+34,tx);
 long now=System.currentTimeMillis();ArrayList<D> l=new ArrayList<>();for(D d:ds.values())if(now-d.t<15000)l.add(d);l.sort((a,b)->Integer.compare(b.r,a.r));int i=0;for(D d:l){float rr=(float)Math.min(R,Math.max(28,R*Math.min(18,d.m())/18));double a=i++*2.399963;float x=cx+(float)Math.cos(a)*rr,y=cy+(float)Math.sin(a)*rr;p.setColor(Color.rgb(101,230,180));c.drawCircle(x,y,8,p);}
 float py=cy+R+38;tx.setColor(Color.WHITE);tx.setTextSize(22);tx.setTypeface(Typeface.DEFAULT_BOLD);c.drawText("NEAREST SIGNALS",30,py,tx);tx.setTypeface(Typeface.DEFAULT);int y=(int)py+34,shown=0;for(D d:l){if(shown++>=5)break;tx.setTextSize(17);tx.setColor(Color.WHITE);c.drawText(d.n,32,y,tx);tx.setTextSize(14);tx.setColor(Color.rgb(150,174,167));c.drawText(d.r+" dBm   "+String.format(Locale.US,"~%.1f ft",d.m()*3.28084),32,y+21,tx);y+=54;}if(l.isEmpty()){tx.setTextSize(16);tx.setColor(Color.LTGRAY);c.drawText("Searching for Bluetooth LE advertisements…",32,y,tx);}
 y=(int)h-105;tx.setColor(Color.WHITE);tx.setTextSize(20);tx.setTypeface(Typeface.DEFAULT_BOLD);c.drawText("PHONE CAPABILITIES",30,y,tx);tx.setTypeface(Typeface.DEFAULT);tx.setTextSize(14);tx.setColor(Color.rgb(150,174,167));PackageManager pm=getPackageManager();boolean ble=pm.hasSystemFeature(PackageManager.FEATURE_BLUETOOTH_LE),uwb=Build.VERSION.SDK_INT>=31&&pm.hasSystemFeature("android.hardware.uwb"),rtt=Build.VERSION.SDK_INT>=28&&pm.hasSystemFeature(PackageManager.FEATURE_WIFI_RTT);c.drawText("BLE: "+yn(ble)+"     UWB: "+yn(uwb)+"     Wi-Fi RTT: "+yn(rtt),30,y+28,tx);tx.setTextSize(12);c.drawText("Distance is estimated; dot angle is not direction.",30,y+51,tx);}
 String yn(boolean b){return b?"YES":"NO";}}
}